### ISSUE TITLE
Updated to Xcode 8 , 20+ errors

### ISSUE THREAD

**Issue by MchlG** [delannoyk/SoundcloudSDK#25] opened 2016-09-19 16:25 UTC
I updated Xcode to version 8.0 and am now getting 20+ errors coming from ImageURLs.swift, TrackRequest.swift, PlaylistRequest.swift and UserRequest.swift. Most of them are fix-it errors saying "value of optional type NSURL? not unwrapped..." . Is there any fix for this or does anyone know why this is happening? Thanks

Note: I am using swift 2.3

**Comment by delannoyk** [comment] 2016-09-20 09:44
Duplicate of #24 
I pushed a version that uses Swift 2.3 (version 0.9.1) let me know if you face any issue :)

**Closed as completed by delannoyk** 2016-09-20 09:44 UTC

**Comment by MchlG** [comment] 2016-09-20 14:09
Awesome thank you ! All errors are gone. For some reason I am unable to login to Soundcloud and get any of the user's information. Nothing is logged to the console except 

2016-09-20 10:08:31.666707 <APPNAME>[1866:406905] [MC] System group container for systemgroup.com.apple.configurationprofiles path is /private/var/containers/Shared/SystemGroup/systemgroup.com.apple.configurationprofiles
2016-09-20 10:08:31.680209 <APPNAME>[1866:406905] [MC] Reading from public effective user settings.

I think this has to do with changes iOS 10 though.
