### ISSUE TITLE
Issue using Querying for Track by Identifier

### ISSUE THREAD

**Issue by OnyxDrift** [delannoyk/SoundcloudSDK#9] opened 2016-02-16 23:05 UTC
Whenever I try to use the following line of code, I get a "Forbidden" error and I cannot figure out why:

Session.login(self, completion: {(result: SimpleAPIResponse<Session>) -> Void in
})

I am correctly setting the clientIdentifier, clientSecret, and redirectURI before use of the above code.

I've been at this for the past two hours and can't really figure out what the deal is.. Hopefully someone has had a similar experience and can help.

**Comment by delannoyk** [comment] 2016-02-17 09:03
Hi! Do you still need help or is this solved?

**Comment by OnyxDrift** [comment] 2016-02-17 18:18
It was an issue with my code.. I resolved that and can successfully login with Session.login now. I now have a new problem that I am trying to work through; I have already written code that queries/searches SoundCloud (without the use of SoundcloudSDK) and returns an array of my own custom track objects, which I would like to leave in place. Now I want to use SoundcloudSDK to "favorite" this track on behalf of the authenticated user.

Step 1: I retrieve the Track's Identifier from my custom object.
Step 2: I use "Tracks.track(identifier: Int, completion: SimpleAPIResponse<Track> -> Void)" to then create a Track struct that I can then use in the following step to favorite on behalf of the user.

After the second step, I would use:

let track: Track
track.favorite(userIdentifier: Int, completion: SimpleAPIResponse<Bool> -> Void)

To favorite on behalf of the user, but for some reason Step 2 keeps failing and it doesn't make sense to me as to why as you do not need an authenticated user to do any "Track Querying".

_Note_ Just noticed that it's very hit or miss, I just got a successful, working track response, but then majority of the time, during failure, this will print to console..

2016-02-17 13:17:05.305 Mix Up[8288:3099493] _BSMachError: (os/kern) invalid capability (20)
2016-02-17 13:17:05.306 Mix Up[8288:3099899] _BSMachError: (os/kern) invalid name (15)

Any ideas?

**Comment by delannoyk** [comment] 2016-02-17 18:28
This log doesn't come from the library.

Also, the SDK was designed to be used with custom objects but I might work on that to make some static methods that just use identifiers. Also, this might generates new errors. If you want, you can open another issue for this so that I don't forget.

So to answer on your issue on Step 2, you do not need to have a logged user at that time. But to favorite a Track, you need to. But as for why the `Track.track(identifier, completion)` doesn't work, I don't know. What error does it give back?

**Comment by OnyxDrift** [comment] 2016-02-17 21:02
Yes, but the client_ID still needs to be set, I believe. It appears when looking at the error I am receiving a ".CredentialsNotSet". Please bare with me as I am very new to handling/working with oAuth2.

In my app, I have a settings menu where I have the login flow working fully, but it appears when I run a new instance of my application (from XCode > Build then Run, begins new instance of app) it loses the Session and anything I've done in a previous instance to authenticate a SoundCloud account.

If I open the app in a new instance, login to the SC account and then attempt to use any of the SoundCloudSDK functions, it appears things are successful. So, I guess my issue is just getting the Soundcloud and Session structs to persist through new instances of my app, which I have not a clue on how to do.

Again thank you for all your help!

-----_Added_----- 
Just tried adding code to favorite the track after getting the Track struct.. Getting the Track struct is successful, but favoriting is still failing even after re-logging into SC Account after new app instance

I'm going to try all this in a fresh/blank app to see what happens. Will let you know.

**Comment by OnyxDrift** [comment] 2016-02-17 21:29
Okay, so I started a blank project with a VC containing two buttons.. one firing off the Session.login "flow" and a second button that attempts to favorite a track.. I've added the output that I am receiving to the console. Hopefully this can narrow it down to what I am doing wrong, programmatically, cause I don't believe it has anything to do with the SoundcloudSDK. Obviously, I click the "login" button and authenticate before attempting to favorite.

`
@IBAction func buttonPressed(sender: AnyObject) {
        Soundcloud.clientIdentifier = "_MY CLIENT_ID_"
        Soundcloud.clientSecret = "_MY CLIENT_SECRET_"
        Soundcloud.redirectURI = "http://example.com/callback"

```
    Session.login(self, completion: {(result: SimpleAPIResponse<Session>) -> Void in
        print("SC Login Occurred?")
        print(result.response.isSuccessful)
        print(result.response.error)
    })
}

@IBAction func favButtonPressed(sender: AnyObject) {
    print(Soundcloud.clientIdentifier)

    Track.track(98252800, completion: {(result: SimpleAPIResponse<Track>) -> Void in

        let track = result.response.result

        print("Track Pull")
        print(track?.title)
        print("Successful? :" + String(result.response.isSuccessful))
        print("Error? :" + String(result.response.error))

        let session = Soundcloud.session
        session?.me({(result: SimpleAPIResponse<User>) -> Void in

            let user = result.response.result

            print("User Pull")
            print(user?.username)
            print("Successful? :" + String(result.response.isSuccessful))
            print("Error? :" + String(result.response.error))

            track!.favorite((user?.identifier)!, completion: {(result: SimpleAPIResponse<Bool>) -> Void in

                print("User Track Favorite")
                print("Successful? :" + String(result.response.isSuccessful))
                print("Error? :" + String(result.response.error))

                let session = Soundcloud.session

            })
        })
    })

}
```

`

Console Output:

SC Login Occurred?
true
nil
Optional("a67778b5a6ba4cdf4758ada46223d901")
Track Pull
Optional("Alley Boy Ft. Kevin Gates & Starlito - Long Haul")
Successful? :true
Error? :nil
User Pull
Optional("shiraqueth")
Successful? :true
Error? :nil
User Track Favorite
Successful? :false
Error? :Optional(Soundcloud.SoundcloudError.Forbidden)

-----Added----- 
I breakpointed on the "let session = Soundcloud.session" and it is not a valid session that would allow any user authenticated functions from SoundcloudSDK to perform successfully. Maybe you could help me out a little here as I just am confused as to why, in the same instance of the app, when I authenticate myself, Soundcloud.session would change, without a Session.refresh, once I have authenticated. 

Thanks for the help, I am trying to work through this as best I can, on my own.

-----Added----- 
This is also being spit out to console during Session.Login flow

2016-02-17 17:48:39.665 SCSandBox[8480:3157854] -canOpenURL: failed for URL: "org-appextension-feature-password-management://" - error: "This app is not allowed to query for scheme org-appextension-feature-password-management"

**Comment by kseniya-hydric** [comment] 2016-02-22 05:01
I am having the same issue with favouriting and unfavoriteing tracks. It always gives me Forbidden even if I'm logged in and even if I refresh the session. There is definitely a problem here. Please help us?

**Comment by OnyxDrift** [comment] 2016-02-22 06:00
I wonder if Soundcloud's API's have disabled the ability to allow an authenticated user to favorite/unfavorite tracks, across the board? They have recently been closing off their "platform", along with other changes to SC, in hopes of generating positive revenue. The company itself seems to have high hopes for the future as they have signed two deals with 2 of 3 of the largest music labels.. allowing them to pursue their hopes of a Spotify like streaming experience with the addition of user created content to their catalogue. I hope this is not the case though.. just recently they did create a rate limit of 15,000 playbacks on stream URL's for their "sounds", per client_ID, per day.

I don't think this would be the case though, because why even have an API offering at all, at that point.

**Comment by kseniya-hydric** [comment] 2016-02-22 06:11
I don't think thats the case because it worked on the web version of what I am doing, which calls their API  via web rather than iOS. I think there's a bug somewhere in this library. Hopefully @delannoyk can help us :)

**Comment by OnyxDrift** [comment] 2016-02-22 06:12
Okay, cool! Good to know that the functionality is intact on SC's end of things. Thanks!

**Comment by kseniya-hydric** [comment] 2016-02-22 23:41
@delannoyk Do you think this can be fixed on your end?

**Comment by delannoyk** [comment] 2016-02-23 06:15
I think this is because you try to favorite already favorited track but I don't have time to check right now. I'll look later tonight!

**Comment by OnyxDrift** [comment] 2016-02-23 06:25
Thank you for giving us your time to look into this! By the way, just trying to help here, but it appears that it still is receiving error as "forbidden" whether track is favorited already or not. Again, thank you so much!

**Comment by delannoyk** [comment] 2016-02-23 18:55
The good news is that I can reproduce it. The bad news is that I don't know yet where that might come from...

**Comment by delannoyk** [comment] 2016-02-23 19:16
And the other good news is a new version fixes it :) Seems like Soundcloud doesn't accept HTTP Payload anymore and every parameters has to be in the URL query string.
Anyway, have fun guys and let me know if that works out for you!

BTW: Use 0.7.1 :)

**Closed as completed by delannoyk** 2016-02-23 19:16 UTC

**Comment by OnyxDrift** [comment] 2016-02-23 20:01
@delannoyk thank you so much buddy! I appreciate it!! =D

**Comment by kseniya-hydric** [comment] 2016-02-23 23:18
Awesome! Thank you so much :) and thanks for this library, love it

**Comment by kseniya-hydric** [comment] 2016-03-11 00:07
@delannoyk This is actually a new issue that started happening about 3 days ago (not sure whether to create a new issue, thought I'd ask first) but the refreshSession started to always fail unless you literally just signed in to Soundcloud. I wonder if Soundcloud changed how long you are allowed to leave it before allowing to refresh a session. Just wondering if you know anything about that? Only last week when i left it for less than 24 hours i was able to refresh the session and was logged in again but now it always fails. No code has been changed. Hope you can help. Thanks!

**Comment by delannoyk** [comment] 2016-03-11 17:19
I'm not seeing this in my app. Anyway, since this requires a specific state, can you tell me what error it fails with?

**Comment by kseniya-hydric** [comment] 2016-03-14 00:49
Strange but its working fine again now and I haven't touched it. Refreshes the session ok now so no worries :)
